// <auto-generated />
using System;
using ApiRelacionPersonas.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRelacionPersonas.Migrations
{
    [DbContext(typeof(RelacionPersonaDbContext))]
    [Migration("20221014011547_TipoDni")]
    partial class TipoDni
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiRelacionPersonas.Domain.Entities.TipoDni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDni");
                });

            modelBuilder.Entity("ApiRelacionPersonas.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoDniId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("ApiRelacionPersonas.Entities.Persona", b =>
                {
                    b.HasOne("ApiRelacionPersonas.Domain.Entities.TipoDni", "TipoDni")
                        .WithMany()
                        .HasForeignKey("TipoDniId");

                    b.Navigation("TipoDni");
                });
#pragma warning restore 612, 618
        }
    }
}
